ALTER TABLE films
  ADD COLUMN IF NOT EXISTS year INT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS kp_is_series BOOLEAN,
  ADD COLUMN IF NOT EXISTS kp_episodes_count INT,
  ADD COLUMN IF NOT EXISTS kp_seasons_count INT,
  ADD COLUMN IF NOT EXISTS kp_id INT;

ALTER TABLE series
  ADD COLUMN IF NOT EXISTS year INT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS kp_is_series BOOLEAN,
  ADD COLUMN IF NOT EXISTS kp_episodes_count INT,
  ADD COLUMN IF NOT EXISTS kp_seasons_count INT,
  ADD COLUMN IF NOT EXISTS kp_id INT;


