ALTER TABLE films
  ADD COLUMN IF NOT EXISTS my_rating FLOAT,
  ADD COLUMN IF NOT EXISTS opinion TEXT;

ALTER TABLE series
  ADD COLUMN IF NOT EXISTS my_rating FLOAT,
  ADD COLUMN IF NOT EXISTS opinion TEXT;


