ALTER TABLE films
  ADD COLUMN IF NOT EXISTS director TEXT,
  ADD COLUMN IF NOT EXISTS budget BIGINT,
  ADD COLUMN IF NOT EXISTS revenue BIGINT,
  ADD COLUMN IF NOT EXISTS genres TEXT[],
  ADD COLUMN IF NOT EXISTS actors TEXT[];

ALTER TABLE series
  ADD COLUMN IF NOT EXISTS director TEXT,
  ADD COLUMN IF NOT EXISTS budget BIGINT,
  ADD COLUMN IF NOT EXISTS revenue BIGINT,
  ADD COLUMN IF NOT EXISTS genres TEXT[],
  ADD COLUMN IF NOT EXISTS actors TEXT[];


